config/routes.rb
Rails.application.routes.draw do
  root 'entries#index'
  get 'entries/index'
  get 'entries/show'
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/signup',  to: 'users#new'
  get '/login',    to: 'sessions#new'
  post '/login',   to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :entries
  resources :users
  resources :comments, only: [:create, :destroy]

  resources :entries do
    resources :comments, only: [:create]
  end

  resources :entries do
    resources :bookmarks, only: [:create, :destroy]
  end

  resources :users do
    resources :bookmarks, only: [:index]
  end

  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :feed
  has_many :comments, dependent: :destroy
  has_many :bookmarks, dependent: :destroy

  def bookmarked_by?(user)
    bookmarks.where(user_id: user).exists?
  end
end

app/controllers/entries_controller.rb
class EntriesController < ApplicationController
  before_action :set_entries, only: :index

  def index
    @pagy, @entries = pagy(@entries.order('published desc'), items: 9)
  end

  def show
    @entry = Entry.find(params[:id])
    @pagy,@comments = pagy(@entry.comments.all, items: 9)

  end

   private
    # def set_feed
    #   @feed = Feed.find(params[:id])
    # end

    def set_entries
      @entries = Entry.all
    end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/index.html.erb
<% provide(:title, "ホーム") %>
<div class="mb-3 w-75 mx-auto text-center">
  <h1>ホーム</h1>
</div>
<% @entries.each_slice(3) do |entry1, entry2, entry3| %>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <div class="col">
      <% if entry1 != nil %>
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= link_to entry1.title, entry1 %></h5>
            <p class="card-text"><i>- <%= link_to entry1.feed.name, entry1.feed.url %> </i></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><i> published <%= time_ago_in_words(entry1.published) %> ago.</i></small>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col">
      <% if entry2 != nil %>
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= link_to entry2.title, entry2 %></h5>
            <p class="card-text"><i>-  <%= link_to entry2.feed.name, entry2.feed.url %> </i></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><i> published <%= time_ago_in_words(entry2.published) %> ago.</i></small>
          </div>
        </div>
      <% end %>
    </div>

    <div class="col">
      <% if entry3 != nil %>
        <div class="card h-100">
          <div class="card-body">
            <h5 class="card-title"><%= link_to entry3.title, entry3 %></h5>
            <p class="card-text"><i>-  <%= link_to entry3.feed.name, entry3.feed.url %> </i></p>
          </div>
          <div class="card-footer">
            <small class="text-muted"><i> published <%= time_ago_in_words(entry3.published) %> ago.</i></small>
          </div>
        </div>
      <% end %>
    </div>
  </div>
<% end %>

<div class="d-flex justify-content-center">
  <%== pagy_bootstrap_nav(@pagy) %>
</div>

app/views/entries/show.html.erb
<% provide(:title, @entry.title) %>

<div class="card text-center col-8 mx-auto">
  <div class="card-header">
    <i><%= link_to @entry.feed.name, @entry.feed.url %></i>
  </div>
  <div class="card-body">
    <h3 class="card-title"><%= link_to @entry.title, @entry.url %></h3>
    <p><%= link_to "続きを読む", @entry.url, class: "btn btn-primary" %></p>
    <% if @entry.bookmarked_by?(current_user) %>
      <span>
        <%= link_to entry_bookmark_path(@entry), class: "favorite", method: :delete do %>
          <i class="fa fa-star fa-2x" aria-hidden="true"></i>
        <% end %>
      </span>
    <% else %>
      <span>
        <%= link_to entry_bookmarks_path(@entry), class: "unfavorite", method: :post do %>
          <i class="fa fa-star-o fa-2x" aria-hidden="true"></i>
        <% end %>
      </span>
    <% end %>
  </div>
  <div class="card-footer text-muted">
    <i> published <%= time_ago_in_words(@entry.published) %> ago.</i>
  </div>
</div>

<% if logged_in? %>
  <div class="col-6 mx-auto">
    <section class="comment-form">
      <%= render 'shared/comment_form' %>
    </section>
    <section>
      <% @comments.each do |comment| %>
        <p><%= link_to comment.user.name, comment.user %></p>
        <p><%= comment.content %></p>
      <% end %>
    </section>
  </div>
  <div class="d-flex justify-content-center">
    <%== pagy_bootstrap_nav(@pagy) %>
  </div>
<% end %>